### ISSUE TITLE
Scalar type hints

### ISSUE THREAD

**Issue by robske110** [svilex/SkyWars-PocketMine#1]
#### Issue description

You used scalar type hints, this will not work in php5 and they are useless (so no clearSky support)

### Errors - CrashDumps

```
Soon...
```

#### Versions

- **SW_VERSION**: 0.1
- **POCKETMINE**: ClearSky
- **PHP**: 5

**Comment by svilex** [comment]
if you download the release zip you can find the php5 version

**Comment by svilex** [comment]
they aren't useless

**Comment by robske110** [comment]
But why do you use scalar type hints at all

**Comment by robske110** [comment]
They are useless

**Comment by robske110** [comment]
And you should, if you realy need them make a folder where i can download source without them

**Comment by svilex** [comment]
you're right , i'm going to add this folder
