### ISSUE TITLE
Idea :D

### ISSUE THREAD

**Issue by RedstoneAlmeida** [svilex/SkyWars-PocketMine#11]
## Players Mode
- Spectator
- setHealth and setMaxHealth in Config
- setEffects in Config
- Kits
- Enchanted Itens(for Genisys)

**Comment by svilex** [comment]
- spectator: will be added
- health: useless?
- effects: this isn't a skywars related thing, use an external plugin for this
- kits: same as effects
- enchanted items: won't be added.soon will be added the possibility to choose chest contents

**Comment by Tolo0** [comment]
you could use AdvancedKits plugin. you can set up enchanted kits... for effects. you could get ItemEffects plugin. and set witch items give effects.

**Comment by RedstoneAlmeida** [comment]
sobre o "health" eu quis dizer colocar opção para setar o limite de vida do player no skywars pela configuração assim podendo fazer um skywars mais longo

**Comment by RedstoneAlmeida** [comment]
just a question, is I'm also coder of pocketmine, I can "edit" plugin for me to be able to put the editable items in bau by setting? to facilitate my server

**Comment by svilex** [comment]
>just a question, is I'm also coder of pocketmine, I can "edit" plugin for me to be able to put the editable items in bau by setting? to facilitate my server

@RedstoneAlmeida sure you can.

>on the "health" I mean put option to set the life Limit player in skywars the configuration so can make a longer skywars

i'm not understanding

**Comment by RedstoneAlmeida** [comment]
## Other Idea
- Add option from /sw join <arena>
the /sw join would be good to place for example in mobs as slapper would be very grateful if you can: D

**Comment by svilex** [comment]
>Add option from /sw join the /sw join would be good to place for example in mobs as slapper would be very grateful if you can: D

thanks for the idea. `/sw join [SWname]` will be added

**Comment by RedstoneAlmeida** [comment]
## Other Idea
- Add option from enter in random arenas tipe... /sw randomjoin

**Comment by svilex** [comment]
>Add option from enter in random arenas type... /sw randomjoin

no
