### ISSUE TITLE
SIGN SUGGESTION

### ISSUE THREAD

**Issue by iMOEchan** [svilex/SkyWars-PocketMine#15]
Hello Slivex can you make a sign format like SurvivalGamesV3 by ImagicalGamer ?

Thanks :)

https://github.com/ImagicalGamer/SurvivalGamesV3

**Comment by Driesboy** [comment]
????

**Comment by iMOEchan** [comment]
Sorry but the format sign is ugly

**Comment by svilex** [comment]
@iMOEchan You can change the signs formats modifying the config file
