### ISSUE TITLE
SIGN FORMAT ON SW_configs.yml NOT WORKS!

### ISSUE THREAD

**Issue by iMOEchan** [svilex/SkyWars-PocketMine#19]
## Versions

- **v0.6**: 

- **GENISYS**: 

- **PHP7**:

**Comment by svilex** [comment]
is working for me

**Comment by svilex** [comment]
@iMOEchan use v0.6dev instead

**Comment by iMOEchan** [comment]
Yeah
1st line: §c[§6SW§c]
2nd line: §e{SWNAME}

Then i type it in sign
sw
ICE

but it's not worked :(

**Comment by HyGlobalHD** [comment]
Maybe It's Because u using color and in readme doesn't shows that the sign format is like thats

**Comment by iMOEchan** [comment]
Argh, so I can't use color ._. ?

**Comment by HyGlobalHD** [comment]
U can if u edit the plugin properly.

**Comment by svilex** [comment]
@HyGlobalHD No.

@iMOEchan There is any message in chat when you place the sign?

**Comment by svilex** [comment]
@iMOEchan Maybe the arena doesn't exists or you didn't set spawns?

**Comment by iMOEchan** [comment]
I was set spawns. It's work when i created a sign but the format didn't works

Image : http://i.hizliresim.com/X4YpM6.jpg

**Comment by oGalatico** [comment]
svile this error on the card arrived in version 0.6 - When you create an
arena and sets the spawns and etc. ai vice poe the board says that there
has been created one plate there appears nothing n and error ;-;
Em 21/05/2016 4:41 AM, "svilex" <notifications@github.com> escreveu:

**Comment by svilex** [comment]
@oGalatico i can't understand you

@iMOEchan try `/sw signdelete` then place the sign again

**Comment by svilex** [comment]
@iMOEchan are you trying to place 2 signs for the same arena ?

**Comment by oGalatico** [comment]
;-; ?
Em 21/05/2016 8:18 AM, "svilex" <notifications@github.com> escreveu:

@oGalatico <https://github.com/oGalatico> i can't understand you

@iMOEchan <https://github.com/iMOEchan> try /sw signdelete then place the
sign again

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/svilex/SkyWars-PocketMine/issues/19#issuecomment-220772357>

**Comment by iMOEchan** [comment]
Same :(

“@iMOEchan are you trying to place 2 signs for the same arena ?”
NO

**Comment by oGalatico** [comment]
Nooooooooo
Em 21/05/2016 9:16 AM, "iMOEchan" <notifications@github.com> escreveu:

**Comment by svilex** [comment]
@iMOEchan Please tell me all the steps needed to reproduce this issue.

If i can't reproduce the bug i will close this issue

**Comment by iMOEchan** [comment]
1.) I edited the format sign on SW_configs.yml
1st line: §c[§6SW§c]
2nd line: §e{SWNAME}
2.) I maked an arena and set spawns
3.) I maked a sign
sw
SWI
(But didn't work)
4.) I deleted the sign with command /sw signdelete SWI
5.) I maked sign again for SWI arena but the format didn't work

**Comment by iMOEchan** [comment]
SOLVED :)

**Comment by svilex** [comment]
this is a genisys bug .

**Comment by svilex** [comment]
@iMOEchan > SOLVED :)

How?

**Comment by iMOEchan** [comment]
Hmm maybe this plugin :(  i deleted sw_signs.db and created a sign again :) nah the issue is if I make a sign format for an arena then delete it with /sw signdelete <name> or destroy the sign then create a sign again for same arena the format didn't work :) I hope you can fix it

**Comment by svilex** [comment]
> Hmm maybe this plugin :( i deleted sw_signs.db and created a sign again :) nah the issue is if I make a sign format for an arena then delete it with /sw signdelete or destroy the sign then create a sign again for same arena the format didn't work :) I hope you can fix it

no
