### ISSUE TITLE
cannot create arena

### ISSUE THREAD

**Issue by Driesboy** [svilex/SkyWars-PocketMine#20]
## Issue description
i will make new arena with name Skywars3
its my 2de map but it dont work!

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: v0.6dev

- **POCKETMINE**: Genisys

- **PHP**: 7.0.4

**Comment by svilex** [comment]
you can't use numbers for the arena name

**Comment by Driesboy** [comment]
Why?
Op 20-mei-2016 19:26 schreef "svilex" <notifications@github.com>:

**Comment by svilex** [comment]
because /sw create is using ctype_alpha() to avoid SQL injections and i don't have time to change/replace it :stuck_out_tongue_winking_eye:
