### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrDoni98** [svilex/SkyWars-PocketMine#21]
## Issue description

Ошибка в консоли, + игра начинает себя странно вести
## Errors - CrashDumps

```
[12:19:28] [Server thread/CRITICAL]: Could not execute task svile\sw\SWtimer: Call to a member function getAttribute() on null     
[12:19:28] [Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/Play
er" at line 4320 
```

## Versions

- **SW_VERSION**: v0.6dev

- **POCKETMINE**:  Genisys 1.1dev-390 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Ed
ition v0.14.2 alpha (protocol version 70) 

- **PHP**: 7

**Comment by svilex** [comment]
how to reproduce?

**Comment by MrDoni98** [comment]
i don't know((

**Comment by svilex** [comment]
@MrDoni98 please try [this](https://transfer.sh/upDC3/sw-svile.phar) phar .

**Comment by BogdanMakarchuk** [comment]
MrDoni98 my friend, and we have a problem with your plugin. He's super, but for some reason, produces errors in the console. The error above! When this error starts, then the particular arena stops working countdown before the game starts! Decide please!

**Comment by svilex** [comment]
@BogdanMakarchuk use the phar i linked above

**Comment by BogdanMakarchuk** [comment]
Thank you:) And when the 0.7 update?

**Comment by svilex** [comment]
@BogdanMakarchuk @BogdanMakarchuk once i added some new features and i fix some bug :)

**Comment by BogdanMakarchuk** [comment]
OK, I'll wait. And thanks for the plugin)

**Comment by BogdanMakarchuk** [comment]
Still produces errors, help!!

**Comment by BogdanMakarchuk** [comment]
[13:45:53] [Server thread/CRITICAL]: Could not execute task svile\sw\SWtimer: Call to a member function getAttribute() on null
[13:45:53] [Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 4320

**Comment by BogdanMakarchuk** [comment]
fix?

**Comment by svilex** [comment]
@BogdanMakarchuk [maybe fixed](https://transfer.sh/fZB13/sw-svile.phar)

**Comment by BogdanMakarchuk** [comment]
Ok, test

**Comment by BogdanMakarchuk** [comment]
And you can custom write a plugin?

**Comment by svilex** [comment]
@BogdanMakarchuk 
> And you can custom write a plugin?

What do you mean?

**Comment by BogdanMakarchuk** [comment]
Well, I need a special plugin for my server)

**Comment by svilex** [comment]
> @BogdanMakarchuk :  Well, I need a special plugin for my server)

Contact me privately

**Comment by BogdanMakarchuk** [comment]
Ok

**Comment by svilex** [comment]
@MrDoni98 @BogdanMakarchuk  , fixed?

**Comment by MrDoni98** [comment]
Yes
