### ISSUE TITLE
Invisible players after a game

### ISSUE THREAD

**Issue by ByZikenPE** [svilex/SkyWars-PocketMine#24]
Hey ! Some people after a SW game become invinsible ( like God mod ) We can't touch them :/ there is No crashDumps or anyrhings like that :( maybe You know where it come from ?

## Versions
- **SW_VERSION**: 0.6 ( The Last one )

- **POCKETMINE**: Genisys 0.14.3

- **PHP**: 2.0.0

**Comment by svilex** [comment]
are you using spectator mode? please use the last plugin version: 0.6dev

**Comment by ByZikenPE** [comment]
I remove spectator mode and The Bug still here, and i am using The Last
version :(

**Comment by svilex** [comment]
please to be sure try this one: https://transfer.sh/KmgSa/sw-svile.phar

**Comment by ByZikenPE** [comment]
I gonna try and i remake a issu If The Bug still

**Comment by ByZikenPE** [comment]
Still The same Bug i found The Probleme ! When a players join a game and The players disconnect and reconnect je become invinsible

**Comment by svilex** [comment]
so , to reproduce this i need to:

- join an arena
- quit the server
- join the server
- and now i'm invisible?

**Comment by ByZikenPE** [comment]
Yes

**Comment by svilex** [comment]
i can't reproduce

**Comment by ByZikenPE** [comment]
:/

**Comment by Driesboy** [comment]
do you have join command?

**Comment by Driesboy** [comment]
and what server software do you have

**Comment by svilex** [comment]
A bug like this happens when a death player is teleported in the default level when the game is over, maybe you meant that ?

**Comment by svilex** [comment]
You should try with the spectator mode enabled.

**Comment by ByZikenPE** [comment]
Already try and same

**Comment by ByZikenPE** [comment]
Well i think The plugin think The entiti still in The game but No so The player is out of The game but hé can't be hit because The plugin think he is in The game

—
Passez un bon moment avec MailTime(http://mailti.me/m|8)

**Comment by svilex** [comment]
>@ByZikenPE: Well i think The plugin think The entiti still in The game but No so The player is out of The game but hé can't be hit because The plugin think he is in The game

If the player can't be hit , It has nothing to do with invisibility you know?
