### ISSUE TITLE
There İs No Minimum Players To Start Count

### ISSUE THREAD

**Issue by Heroata** [svilex/SkyWars-PocketMine#29]
What about minimum players to start count?

**Comment by svilex** [comment]
what about your eyes ?

https://github.com/svilex/SkyWars-PocketMine/blob/master/SW/resources/SW_configs.yml#L39

**Comment by Heroata** [comment]
oh why you set it to 1 :( I searched for a command and never think a config anyway thanks

**Comment by svilex** [comment]
1 is the default value , you can change it -.-
