### ISSUE TITLE
SkyWars freezing server.

### ISSUE THREAD

**Issue by KillerXtream** [svilex/SkyWars-PocketMine#32]
## Issue description

Okay, at the moment of creating an arena in a world, example, SkyWars, there is a loop about Unloading world Skywars... Preparing world Skywars... and when that loop reaches 5 mins, server freezes.

## Errors - CrashDumps

No crashdump.
```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: v0.6dev

- **POCKETMINE**: Genisys-dev

- **PHP**: 7

**Comment by svilex** [comment]
there is no loop
