### ISSUE TITLE
Chest's are empty 

### ISSUE THREAD

**Issue by Xelcronia** [svilex/SkyWars-PocketMine#35]
## Issue description
When the game starts, and players go to chests, only to find them empty. 

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: downloaded the latest ZIP file. 

- **POCKETMINE**:  Genisys 0.15.0

- **PHP**: 
Php 7

**Comment by svilex** [comment]
@Xelcronia Did you create the map using pocketmine or is an imported one?

**Comment by Xelcronia** [comment]
Imported.

**Comment by svilex** [comment]
you need to creatw chest tiles

**Comment by Xelcronia** [comment]
@svilex how do i create chest tiles?

**Comment by svilex** [comment]
@Xelcronia placing chests

**Comment by Xelcronia** [comment]
@svilex okay!  Thank you so much! :D

**Comment by Xelcronia** [comment]
@svilex i placed new chests, didn't work :(

**Comment by svilex** [comment]
- Check your configs
- Try with a map generated by pocketmine

**Comment by Xelcronia** [comment]
Okay

**Comment by Driesboy** [comment]
I use a imported map and i dont replace chests and it work for me

**Comment by Xelcronia** [comment]
@Driesboy which version are you using?

**Comment by svilex** [comment]
Chest refill is working in every version

**Comment by Xelcronia** [comment]
Okay. I'll try using it in a different map

**Comment by Xelcronia** [comment]
@svilex i created a new arena using a pocketmine generated map. Chests were still empty :(

**Comment by svilex** [comment]
@Xelcronia still no reason why isn't working for you. since it is working fine for me, if you don't provide a valid description to reproduce, this isn't an issue, is just a person who is using the plugin wrongly

**Comment by Xelcronia** [comment]
@svilex  first i created an arena with an imported world, didn't make any changes in config. After crating the arena successfully and players join, the game starts, but the chests remain empty. I also remade area deleting the old chests and adding new onces, didn't work still. So, i created a new flat world and placed chests and created a new arena. Still, didn't work.

**Comment by svilex** [comment]
@Xelcronia still no reason

**Comment by Xelcronia** [comment]
Okay.  thanks for helping me out the best you could.
