### ISSUE TITLE
SW_Lang.yml is not working

### ISSUE THREAD

**Issue by FaanMaario** [svilex/SkyWars-PocketMine#36]
## Issue description

I wanted to translate into french for my server, but after the change (and the reboot) nothing. Again in english.

## Errors - CrashDumps

Nothing

## Versions

- **SW_VERSION**: 0.6dev

- **POCKETMINE**: Genysis 1.2dev-640

- **PHP**: PHP7

**Comment by svilex** [comment]
That isn't happening to me. Try this sequence:

- stop the server
- delete the plugin folder
- start and then stop the server
- modify the lang.yml
