### ISSUE TITLE
/sw quit & /sw join - Issue

### ISSUE THREAD

**Issue by AirLinesCraft** [svilex/SkyWars-PocketMine#37]
## Issue description
when i do /sw quit or/sw join it doesnt work and only shows the sw commands

## Errors - CrashDumps
 no CrashDumps
```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: v0.6

- **POCKETMINE**: Genisys git-0909f53

- **PHP**: 7

**Comment by svilex** [comment]
Do you know i wrote a readme ?
It is called README because it should be read.

**Comment by AirLinesCraft** [comment]
But how ops can leave the game?

**Comment by svilex** [comment]
@AirLinesCraft surely not using these commands. Since OPs usually doesn't play games on their server i don't care and i'm not going to modify the plugin. If you are able you can modify it yourself
