### ISSUE TITLE
/sw join

### ISSUE THREAD

**Issue by marker98** [svilex/SkyWars-PocketMine#38]
My English is not very good, so I write in Russian and translated into English with the help of google.translate :D

Thank you very much for this plugin! He is very cool but lacks command join. I mean, that would be very convenient if the player entering the chat command /sw join is automatically appeared on the map, which is currently set and the most players.

I hope that you will understand what I have spoken unto ._.

**Comment by svilex** [comment]
@marker98 Test the last commit and let me know

**Comment by marker98** [comment]
When I wrote "/sw join", the server replied "Usage: /sw [create|..."
Did I do something wrong?

**Comment by marker98** [comment]
I replaced the plug completely, but configs and maps left unchanged.

![screenshot_20160721-154357-581](https://cloud.githubusercontent.com/assets/16980972/17023090/3201d38a-4f5a-11e6-98b6-15474b804866.jpg)
![screenshot_20160721-154400-281](https://cloud.githubusercontent.com/assets/16980972/17023091/320b4cf8-4f5a-11e6-9787-01e66af6599c.jpg)

**Comment by svilex** [comment]
OPs can't use /sw join

**Comment by marker98** [comment]
thx muth! :з

**Comment by Kebad45** [comment]
@svilex why do you close the issue if it's not fixed ?

**Comment by svilex** [comment]
@Kebad45 
- This is not the right place to reply, you are talking about your issue
- Your issue was closed because it's invalid
- Something like your issue was already solved here

**Comment by Kebad45** [comment]
@svilex I test with the last version -.-

**Comment by svilex** [comment]
@Kebad45 

Are you op while using the command?
