### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PocketMine-GAD** [svilex/SkyWars-PocketMine#39]
## Issue description

i don't know how to set up a game area.
when i enter "/sw create SWworld 10 10 10" and it show me "must consists of all letters "
but i don't know what mean! could you give me a good example?thx
## Errors - CrashDumps

```
paste here or delete these lines
```plugin version:v0.6
pm:gensisy
php:7

## Versions
<!--- write the plugin version ex. v0.1 -->
- **SW_VERSION**: 

<!--- write the name and the version of the PocketMine fork you are using -->
- **POCKETMINE**: 

<!--- write the php version you are using -->
- **PHP**:

**Comment by PocketMine-GAD** [comment]
Forgive me for not knowing the format

**Comment by svilex** [comment]
so , is working ?
