### ISSUE TITLE
Sell Plugin

### ISSUE THREAD

**Issue by MCPEPluginer16** [svilex/SkyWars-PocketMine#40]
Hi One Peopel is selling your plugin
Prove

https://youtu.be/3LDKFDKCTIU

**Comment by MCPEPluginer16** [comment]
Sorry For bad English :(

**Comment by svilex** [comment]
Thanks :)

**Comment by KairusDarkSeeker** [comment]
y not take the video down?

**Comment by svilex** [comment]
?

**Comment by KairusDarkSeeker** [comment]
I mean take the video down as copyright claim

**Comment by svilex** [comment]
@KairusDarkSeeker are you blind? the video was already removed

**Comment by KairusDarkSeeker** [comment]
@svilex well I guess I am
