### ISSUE TITLE
plugin disabling

### ISSUE THREAD

**Issue by MrDoni98** [svilex/SkyWars-PocketMine#42]
## Errors - CrashDumps

```
ClassNotFoundException: "Class ZipArchive not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
```

## Versions

- **SW_VERSION**: v0.6

- **POCKETMINE**: Genisys (codename "Kyrios")
 API: 2.0.0 (iTX API version 1.9.0)

- **PHP**:  7.0.9

**Comment by MrDoni98** [comment]
use - ZipArchive(); at line 122 and 133

**Comment by svilex** [comment]
recompile php with zip support
