### ISSUE TITLE
Please help me fix a memory leak...

### ISSUE THREAD

**Issue by BudderSticks** [svilex/SkyWars-PocketMine#43]
Genisys Crash Dump Fri Aug 12 04:32:41 PDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 12288 bytes)
File: /src/pocketmine/network/RakLibInterface
Line: 202
Type: E_ERROR

Code:
[193] 		);
[194] 	}
[195] 
[196] 	public function setPortCheck($name){
[197] 		$this->interface->sendOption("portChecking", (bool) $name);
[198] 	}
[199] 
[200] 	public function handleOption($name, $value){
[201] 		if($name === "bandwidth"){
[202] 			$v = unserialize($value);
[203] 			$this->network->addStatistics($v["up"], $v["down"]);
[204] 		}
[205] 	}
[206] 
[207] 	public function putPacket(Player $player, DataPacket $packet, $needACK = false, $immediate = false){
[208] 		if(isset($this->identifiers[$h = spl_object_hash($player)])){
[209] 			$identifier = $this->identifiers[$h];
[210] 			$pk = null;
[211] 			if(!$packet->isEncoded){
[212] 				$packet->encode();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 347b4a0f6c2410faf3fb1e7673d7b663532b6ed6 [Protocol 82; API 2.0.0]
uname -a: Linux lamcpe2 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
PHP version: 7.0.8
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 6 hours 32 minutes 44 seconds
Number of loaded worlds: 5
Players online: 0/20

Loaded plugins:
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
BlockBoost 1.0.0 by  for API(s) 1.13.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.0.0, 2.0.0
SkyWarsDoDo 1.0.0 Reloaded_ENGLISH by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
MicroBattles 2.3.0 by KaitoDoDo+LittleBigMC for API(s) 1.0.0, 2.0.0
SwaggyMOTD 1.0.0 by ImagicalGamer for API(s) 1.0.0, 2.0.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
Functions 1.0 by Ad5001 for API(s) 1.14.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by svilex** [comment]
Are you stupid ?

**Comment by BudderSticks** [comment]
No, I just do not know where else to start a issue... Now, if you think I am stupid, I suggest you leave this converstation.

**Comment by BudderSticks** [comment]
So get put loser. if you don't want to help, get out.

**Comment by iPeedroPvP** [comment]
its a your server memory
Em 20 de ago de 2016 11:20, "BudderSticks" <notifications@github.com>
escreveu:

**Comment by iPeedroPvP** [comment]
Ops, restart your smartphone

**Comment by BudderSticks** [comment]
Hmm, I do have a lot of memory that I do not use. I did try to play around with my pocketmin.yml. (I installed his SkyWars' plugin and it kept crashinglike this. So I deleted it and re-instaleld my old one. It still crashes).

**Comment by svilex** [comment]
@BudderSticks Yes is what i think because:

- What you asked is not related to this plugin, you are not even using this plugin but another (SkyWarsDoDo 1.0.0 Reloaded_ENGLISH by KaitoDoDo)

>I just do not know where else to start a issue

- You don't know? How is this possible there are my contact everywere! Never thought about contacting me privately?
- Never thought about opening an issue [HERE](https://github.com/iTXTech/Genisys/issues) since is the server software you are using?

And i can't not even ask you if you are stupid? :joy::joy::joy::joy::joy:
Where is the problem? i was so rude? really? :cold_sweat:

You're touchy
