### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by iPeedroPvP** [svilex/SkyWars-PocketMine#49]
It has a paid version of Skywars ? If so how much and what adds but?

**Comment by svilex** [comment]
1- Horrible english.
2- What are you talking about?
3- As you can see this plugin is free.

**Comment by iPeedroPvP** [comment]
Sorry my bad english i from brazil don't use this lenguage! - If I give you
the beautiful plugin, you can modify ?
Em 24 de ago de 2016 13:54, "svilex" <notifications@github.com> escreveu:

**Comment by iPeedroPvP** [comment]
donate money..
Em 24 de ago de 2016 14:04, "Pedro Bitercurtt" <henriquep869@gmail.com>
escreveu:

**Comment by svilex** [comment]
I can't understand, contact me privately, this is an issue tracker not a chat
