### ISSUE TITLE
Add join and quit commands away

### ISSUE THREAD

**Issue by SuperAdam47** [svilex/SkyWars-PocketMine#57]
![screenshot_2016-08-28-22-31-42](https://cloud.githubusercontent.com/assets/16169771/18036322/dfec73b4-6d6f-11e6-8d87-9e5649f6ed6f.png)

**Comment by svilex** [comment]
read the readme

**Comment by SuperAdam47** [comment]
İm already read

**Comment by SuperAdam47** [comment]
Join quit commands not working

**Comment by svilex** [comment]
OPs can't use them , you didn't read the readme
