### ISSUE TITLE
Error while creating arena

### ISSUE THREAD

**Issue by AirLinesCraft** [svilex/SkyWars-PocketMine#59]
## Issue description

While creating an arena it appears that an unknowed error ocurred while executing that command (that is /sw create)

## Versions

- **SW_VERSION**: 0.6 dev

- **POCKETMINE**: Genisys

- **PHP**: 7.0

**Comment by AirLinesCraft** [comment]
Here is a print!
![screenshot_2016-08-29-22-15-23 2](https://cloud.githubusercontent.com/assets/19599166/18067795/5a3efa76-6e36-11e6-9ce1-ff823d29d8c7.png)

**Comment by svilex** [comment]
This is not helpful at all. Check your console for the error

**Comment by AirLinesCraft** [comment]
Found!
[Server] Server thread/CRITICAL Unhandled exception executing command 'sw create nether 12 30 600' in sw: Class ZipArchive not found
29.08 19:56:10 [Server] Server thread/CRITICAL ClassNotFoundException: "Class ZipArchive not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by svilex** [comment]
This was fixed [here](https://github.com/svilex/SkyWars-PocketMine/commit/050db6f5c506e2b65dae4719f9e9a056f0db273a) so pls try using the latest phar.

You can download it from [here](https://transfer.sh/115fVU/sw-svile.phar)

**Comment by AirLinesCraft** [comment]
Still showing the same error in console and in game

**Comment by AirLinesCraft** [comment]
Oh and i forgot to say that i am using an online hosting with genisys and the plugins are in a ftp server

**Comment by svilex** [comment]
I'm sure you did something wrong , if the error is the same it means you didn't load the new phar since ZipArchive was REMOVED. Follow these steps:

- stop your server
- replace the plugin with the new phar
- start your server
- let me know

**Comment by AirLinesCraft** [comment]
New error!
[Server] Server thread/CRITICAL Unhandled exception executing command 'sw create trees 12 30 600' in sw: Cannot create phar '/plugins/SW_svile/arenas/trees/trees.tar', file extension (or combination) not recognised or the directory does not exist
29.08 20:44:31 [Server] Server thread/CRITICAL UnexpectedValueException: "Cannot create phar '/plugins/SW_svile/arenas/trees/trees.tar', file extension (or combination) not recognised or the directory does not exist" (EXCEPTION) in "/sw-svile.phar/src/svile/sw/SWcommands" at line 299

**Comment by svilex** [comment]
can you check if this directory exists?

>/plugins/SW_svile/arenas/trees/

**Comment by AirLinesCraft** [comment]
I dont have the arenas paste should i create one?

**Comment by svilex** [comment]
strange, the plugin should create one :/

try deleting the whole plugin folder and restarting your server. the plugin should create the needed folders

**Comment by AirLinesCraft** [comment]
Ok

**Comment by AirLinesCraft** [comment]
Thank You So Much!!!!!!!
It worked!!! Now i can set the slots thx again 😄😄😄😄
