### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Driesboy** [svilex/SkyWars-PocketMine#6]
## Issue description

Please add ranks

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**:  

- **POCKETMINE**: 

- **PHP**:

**Comment by Tolo0** [comment]
use pureperms lol its best to keep the plugin simple so it runs smoothly.  ranks is not needed.

**Comment by Driesboy** [comment]
add permission to do that plz

**Comment by Tolo0** [comment]
u do realise ranks would be a different plugin?

**Comment by Driesboy** [comment]
OnJoin the match

**Comment by Tolo0** [comment]
you can set ranks to different worlds. so when they join a skywars game. it will change there rank to how u set.

**Comment by Tolo0** [comment]
or you could add different ranks to different kits
