### ISSUE TITLE
SW Timer fail!

### ISSUE THREAD

**Issue by BudderSticks** [svilex/SkyWars-PocketMine#62]
So, the SW timer often fails to start the match. So I looked in the server console and found this glitch

05.09 09:29:22 [Server] Server thread/CRITICAL Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/entity/Human" at line 141
05.09 09:29:22 [Server] Server thread/CRITICAL Could not execute task svile\sw\SWtimer: Call to a member function getAttribute() on null

**Comment by svilex** [comment]
write versions or i will ignore this issue

**Comment by BudderSticks** [comment]
Lemme get the version

**Comment by BudderSticks** [comment]
It says version 0.60000

**Comment by svilex** [comment]
it isn't the last

**Comment by BudderSticks** [comment]
Olay, tnanks for the help! I will get the latest version! Idk how

**Comment by svilex** [comment]
You can get it from travis clicking the green "build passing" button under the image in the readme. You will find a download link at the [end of the log](https://travis-ci.org/svilex/SkyWars-PocketMine#L693)

**Comment by BudderSticks** [comment]
Thank you!
