### ISSUE TITLE
[SUGGESTION] Timer

### ISSUE THREAD

**Issue by KairusDarkSeeker** [svilex/SkyWars-PocketMine#63]
hey can I change the timer format to Minutes:Seconds?

**Comment by svilex** [comment]
What do you mean ?

**Comment by KairusDarkSeeker** [comment]
I wanna change the timer like 20:39

**Comment by svilex** [comment]
Explain, better. What do you mean by timer? Maybe link me to a line in the code.

**Comment by svilex** [comment]
If you want to, make a pr and if it's ok i will merge it.

**Comment by KairusDarkSeeker** [comment]
ok
