### ISSUE TITLE
No timer

### ISSUE THREAD

**Issue by TonyWAV** [svilex/SkyWars-PocketMine#65]
## Issue description
No timer

## Errors - CrashDumps

[Server thread/CRITICAL]: ClassNotFoundException: "Class svile\sw\Effect not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

## Versions

- Latest

- Genisys

- Php 7

**Comment by svilex** [comment]
Yes, `svile\sw\Effect` doesn't exist but i'm not using it so, what's your problem?

**Comment by TonyWAV** [comment]
sw/Effect really doesnt exist but how come this problem occur

**Comment by svilex** [comment]
maybe another plugin is trying to use this class ?
when the problem occours?
