### ISSUE TITLE
{help} players can't place blocks

### ISSUE THREAD

**Issue by Epicrafter60** [svilex/SkyWars-PocketMine#67]
I was going through SkyWars plugins in github for my server and I found this one. I think this is a great plugin that I really like however... I found a bug where guests can't place blocks which I just can't accept. I've been spending hours trying to see the plugins and find whats affecting it but I can't seem to find it. I need help in fixing this so please help me out. These are the plugins I'm currently using:

**Comment by Epicrafter60** [comment]
NoAdvertisingPE v1.0.1, AntiHunger v1.0.0, InventoryClear v1.3, TNTRun v1.0.0, iProtector v3.1a, AlwaysSpawn v2.2.2, MSpawns v1.5, SurvivalGamesV3 v3.1.2, BlockBoost v1.0.0, SW_svile v0.6dev, ServerAuth v2.13, BlockCmdPE v1.0.1, No-Drop v1.0, TimeCommander v2.1, SafeFly v1.0.0, BuyCraft v1.2.2, WorldEdit+ v0.01, PocketVote v1.3.1, LBChatFilter v0.0.1, Slapper v1.2.9.6, PvPWorlds v1, ManyWorlds v2.1.0, LBParticles v0.0.1, PurePerms v1.3.7, CustomAlerts v1.6, fineJoin v1, Broadcaster v1.16, SimpleWarp v2.1.1, PureChat v1.4.0

**Comment by svilex** [comment]
if players can't place blocks it's not because of this plugin.
