### ISSUE TITLE
Countdown stops working: Could not execute task svile\sw\SWtimer

### ISSUE THREAD

**Issue by KnightRider0070** [svilex/SkyWars-PocketMine#70]
## Issue description

Skywars count down timer stops working after the 1st game is played.

this problem seems to have occurred with latest MCPE version bump.

0.15.9 - worked fine.
0.15.10 - count down errors occur

## Errors - CrashDumps

[Server thread/CRITICAL]: Could not execute task svile\sw\SWtimer: Call to a member function getAttribute() on null

2016-10-08 [14:58:30] [Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/entity/Human" at line 128

## Versions

V 0.6dev

Genisys_2f820fe

PHP7

**Comment by adamiss5138** [comment]
I have the same problem

**Comment by MattWAnderson** [comment]
Issue appears to be related to this:
https://github.com/iTXTech/Genisys/pull/1946

Disabling Hunger or changing "SetFood" should fix this.

**Comment by svilex** [comment]
could not reproduce

**Comment by KnightRider0070** [comment]
How many Arenas do you recommend playing at once?
This is reproduced with at least 15 players across 3 arenas.

of course it cant be reproduced with 1 game

**Comment by svilex** [comment]
> How many Arenas do you recommend playing at once?
This is reproduced with at least 15 players across 3 arenas.
of course it cant be reproduced with 1 game

-.-
