### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by Misteboss** [svilex/SkyWars-PocketMine#75]
## Issue description

The command join doesn't work and can you add a random join cause its doesn't work, i think you should add a live timer during the fight

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: Last

- ** Genisys Last

- **PHP**: 7.0.0

**Comment by svilex** [comment]
OPs can't use the join command

**Comment by Misteboss** [comment]
But can you add a random join ? And a live timer ?

**Comment by svilex** [comment]
yes i can but i will not

**Comment by Misteboss** [comment]
Why ? Can you explain to me how to do taht so i will make one for my server

**Comment by svilex** [comment]
You should not edit comments to reply -.-
