### ISSUE TITLE
Kill not display / count

### ISSUE THREAD

**Issue by ByZikenPE** [svilex/SkyWars-PocketMine#79]
## Issue description

The plugin do not count a kill i mean when u kill someone it just say that i kill him but u dont rly kill him and my other plugin PVPlevelRPG give exp to the player who kill someone but he dont detect that he kill someone so idk what i can do :/

## Versions

- **SW_VERSION**: 0.6

- **POCKETMINE**: genisys

- **PHP**: 2.0.0 / php7

**Comment by svilex** [comment]
Right

**Comment by ByZikenPE** [comment]
okay i found that was cause only was spectator mod was enable !

ho and if u can add the \n for create new line for winning message and the other message it will be nice ! :)

**Comment by svilex** [comment]
@ByZikenPE You can use _EOL_ as \n

**Comment by svilex** [comment]
sure because players are set to spectators and doesn't die

**Comment by ByZikenPE** [comment]
Hum not sur How this is working I do \EOL or I just pute EOL somewhere for
do à other line ?


Like


================\EOL
You won the game\EOL
================

Le dim. 20 nov. 2016 à 20:33, svilex <notifications@github.com> a écrit :

@ByZikenPE <https://github.com/ByZikenPE> You can use *EOL* as \n

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/svilex/SkyWars-PocketMine/issues/79#issuecomment-261799516>,
or mute the thread

**Comment by svilex** [comment]
There are already strings using it in the (default lang)[https://github.com/svilex/SkyWars-PocketMine/blob/master/SW/src/svile/sw/SWmain.php#L229]

**Comment by ByZikenPE** [comment]
I got it thanks !
