### ISSUE TITLE
how to load this plugin 2x

### ISSUE THREAD

**Issue by Driesboy** [svilex/SkyWars-PocketMine#88]
## Issue description

i need to load this plugin 2x

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: 

- **POCKETMINE**: 

- **PHP**:

**Comment by svilex** [comment]
what do you mean?

**Comment by Driesboy** [comment]
i have made a sg plugin from this and i want use also the original

**Comment by Driesboy** [comment]
but if i change the name 
and removed the sleep it load 1 arena en itstops

**Comment by Driesboy** [comment]
k i know its not a issue
