### ISSUE TITLE
Suggestion! - Kits

### ISSUE THREAD

**Issue by austina1212** [svilex/SkyWars-PocketMine#89]
Maybe, since not everyone wants kits. Either make it so you could enable them or disable them from the config? And or make a seperate plugin that interconnect with this one for kits!

Example:

Ranks with the perm skywars.kit.VIP get VIP kit on join.
Ranks with perm skywars.kit.VIP+ get VIP+ kit on join.

This would be great for our network!

// Stcraft network Staff Team!

**Comment by Driesboy** [comment]
#34 
![68747470733a2f2f692e6779617a6f2e636f6d2f66666334366336363437373766313538643832306238303565356132353562322e706e67](https://cloud.githubusercontent.com/assets/15795262/21577314/fed07cfa-cf56-11e6-8716-d0e58385d7b8.png)

**Comment by austina1212** [comment]
...?
