### ISSUE TITLE
Idea ?

### ISSUE THREAD

**Issue by majovec** [svilex/SkyWars-PocketMine#9]
To add to the plugin and the kits after the player?

**Comment by svilex** [comment]
i can't understand the language you are using
Il 26/apr/2016 17:29, "majovec" <notifications@github.com> ha scritto:

**Comment by majovec** [comment]
kits (dia armor,gol......) for players

**Comment by svilex** [comment]
ok
Il 26/apr/2016 18:06, "majovec" <notifications@github.com> ha scritto:

**Comment by svilex** [comment]
i will add kits and economy support soon

**Comment by svilex** [comment]
economy added , kits are not going to be added because it's not a skywars related thing. use external plugins for this purpose
