### ISSUE TITLE
player dont get damage in void

### ISSUE THREAD

**Issue by Driesboy** [svilex/SkyWars-PocketMine#91]
## Issue description

the player dont get damage in void if there is no pvp

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**:  0,6

- **POCKETMINE**: Elywings

- **PHP**: 7.0.14

**Comment by Driesboy** [comment]
why?

**Comment by Driesboy** [comment]
they dont go that and if the no pvp is done it will stop

**Comment by svilex** [comment]
What is this `no pvp` are you talkimg about?

**Comment by Driesboy** [comment]
that nopvp countdown

**Comment by Driesboy** [comment]
https://github.com/svilex/SkyWars-PocketMine/blob/master/SW/resources/SW_configs.yml#L97

**Comment by Xelcronia** [comment]
I think he means is that when players fall off into the void in the first 20 seconds which says "you can't pvp", they won't get killed by the void until those 20 seconds pass.

**Comment by Driesboy** [comment]
yes
