### ISSUE TITLE
CODE

### ISSUE THREAD

**Issue by ISRAPIL** [svilex/SkyWars-PocketMine#92]
The code is not beautiful! It is very difficult to read. I can help with the further development of this plugin!

**Comment by svilex** [comment]
... said the elywing's supporter.

This plugin is "dead" , i'm not making real commits from at least 5 months, if you want to help, well, start making PRs.

> It is very difficult to read

maybe meant to be? i don't think base64 were wrote by mistake

> The code is not beautiful!

I will add text arts like this soon

                _                        
                \`*-.                    
                 )  _`-.                 
                .  : `. .                
                : _   '  \               
                ; *` _.   `*-._          
                `-.-'          `-.       
                  ;       `       `.     
                  :.       .        \    
                  . \  .   :   .-'   .   
                  '  `+.;  ;  '      :   
                  :  '  |    ;       ;-. 
                  ; '   : :`-:     _.`* ;
         [bug] .*' /  .*' ; .*`- +'  `*' 
               `*-*   `*-*  `*-*'
