### ISSUE TITLE
Change/Update of the sign system ?

### ISSUE THREAD

**Issue by Kebad45** [svilex/SkyWars-PocketMine#96]
## Issue description

With the MCPE 1.0.0 Update, the server don't detect when i put sw and Arena1, i think the SignChangeEvent is broken, can you add an other possibility to add sign like a command or something like that ?

## Errors - CrashDumps

```
paste here or delete these lines
```

## Versions

- **SW_VERSION**: 0.6dev

- **POCKETMINE**: Elywing && Pocketmine

- **PHP**: 7.0.2

**Comment by Driesboy** [comment]
IF THE SIGNCHANGEEVENT DONT WORK!! ITS THE SERVER PROBLEM!!!! not a plugin issue

**Comment by Kebad45** [comment]
I know it doesn't work, i ask him to add  the possibility to add a sign via a command cause for the moment the plugin is broken 😅

**Comment by Kebad45** [comment]
@svilex

**Comment by Driesboy** [comment]
mentions dont work

**Comment by svilex** [comment]
i will just disable issues since they're not going to be fixed at least in the near future, i'm sorry
